extends RefCounted

static func run(t: TestKit) -> void:
    var player := AnimationPlayer.new()
    var library := AnimationLibrary.new()
    for spec in [["stand",2.0],["walk",1.0],["run",.72],["pleased",1.9]]:
        var clip := Animation.new()
        clip.length = float(spec[1])
        library.add_animation(str(spec[0]),clip)
    player.add_animation_library("",library)
    var owner := Node3D.new()
    (Engine.get_main_loop() as SceneTree).root.add_child(owner)
    owner.add_child(player)
    var acting := KettleNextActing.new()
    acting.setup(player,"player")
    t.eq(library.get_animation("run").loop_mode,Animation.LOOP_LINEAR,"gait loops")
    t.eq(library.get_animation("pleased").loop_mode,Animation.LOOP_NONE,"reaction is a one-shot")
    acting.update(.1,"walk")
    player.advance(.5)
    acting.update(0,"run")
    t.ok(absf(player.current_animation_position-.36)<.01,"gait switch preserves foot-cycle phase")
    acting.perform("pleased")
    var serial := acting.serial
    acting.update(.8,"stand")
    t.eq(acting.current,"pleased","reaction plays through instead of restarting the idle")
    acting.perform("absent")
    t.eq(acting.serial,serial,"unknown gesture cannot cancel valid acting")
    acting.update(1.2,"stand")
    t.eq(acting.current,"stand","reaction settles after its actual clip duration")
    t.eq(acting.gesture,"","finished gesture is cleared")
    acting.perform("pleased")
    acting.cancel()
    acting.update(0,"stand")
    t.eq(acting.current,"stand","conversation cancellation settles immediately")
    t.ok(acting.serial>serial,"cancellation invalidates old gesture tokens")
    var prior := OS.get_environment("NINEPOINT_PRESENTATION")
    OS.set_environment("NINEPOINT_PRESENTATION", "")
    t.ok(not KettleNextProfile.enabled(),"prototype remains opt-in in the normal gate")
    t.eq(KettleNextProfile.person_path("player","original"),"original","campaign uses original asset without session profile")
    OS.set_environment("NINEPOINT_PRESENTATION", prior)
    owner.free()
