class_name TeachingTests
extends RefCounted


static func run(t: TestKit) -> void:
    t.section("live teaching")
    var fixture := ReviewFactsTests.dying_group()
    fixture.erase("lead_pass")
    var input := ReviewFacts.player_input(fixture)
    var facts := ReviewFacts.build(input)
    t.ok(not facts["group_died"].is_empty(), "two-branch facts preserve group loss")
    t.ok(facts["slow_move"].is_empty(), "no invented pass valuation")
    var policy := TeachingPolicy.new()
    t.ok(policy.question(facts, 3.99, "a").is_empty(), "below threshold is quiet")
    var question := policy.question(facts, 4.0, "a")
    t.ok(question["text"].contains("C3"), "question identifies the real group")
    t.ok(not question["text"].contains("D3"), "question does not give the preferred move")
    t.ok(policy.question(facts, 9.0, "a").is_empty(), "undo retry never repeats the question")
    for i in 4:
        policy.commit_turn()
        t.ok(policy.question(facts, 9.0, str(i)).is_empty(), "five-turn cooldown")
    policy.commit_turn()
    t.ok(not policy.question(facts, 9.0, "next").is_empty(), "cooldown expires after five retained turns")
    for f in [ReviewFactsTests.corner(), ReviewFactsTests.spared_group()]:
        var p := TeachingPolicy.new()
        t.ok(not p.question(ReviewFacts.build(ReviewFacts.player_input(f)), 8.0, "x").is_empty(), "other named facts ask questions")
    var quiet := TeachingPolicy.new()
    t.ok(quiet.question(ReviewFacts.build(ReviewFactsTests.quiet()), 20.0, "x").is_empty(), "score alone cannot invent a question")
    var small := {"region_lost": [{"points": 3, "area": "centre", "anchor": "C3", "members": ["C3"]}]}
    t.ok(quiet.question(small, 8.0, "small").is_empty(), "small region does not interrupt")
    var game := GoGame.new(9)
    game.set_position(PackedByteArray(fixture["cells"]), GoBoard.BLACK)
    var original := TeachingPosition.key(game)
    var copied := game.fork()
    copied.play(int(fixture["actual"]))
    t.eq(TeachingPosition.key(game), original, "analysis fork cannot change live game")
    copied.play(copied.board.from_label("D3"))
    t.ok(TeachingPolicy.reply_note(facts, copied, GoBoard.BLACK, "Wren").contains("one liberty"), "matching reply explains observed atari")
    copied.undo()
    copied.play(copied.board.from_label("J9"))
    t.eq(TeachingPolicy.reply_note(facts, copied, GoBoard.BLACK, "Wren"), "", "different opponent reply stays quiet")
    game.ko_point = game.board.from_label("D3")
    var illegal := ReviewFacts.build(input, game)
    t.ok(illegal.is_empty(), "live facts respect the actual ko restriction")
    game.ko_point = -1
    game.to_move = GoBoard.WHITE
    t.ok(ReviewFacts.build(input, game).is_empty(), "mismatched live snapshot cannot prove a claim")
    var g := GoGame.new(9)
    g.ko_rule = GoGame.KoRule.POSITIONAL_SUPERKO
    g.play_xy(2, 2)
    t.ok(g.undo(), "undo superko placement")
    t.ok(g.is_legal(g.board.idx(2,2)), "undone position does not poison repetition history")
    t.ok(g.play_xy(2,2), "same move can be replayed after undo")
    var forked := g.fork()
    forked.pass_turn()
    forked.undo()
    t.eq(TeachingPosition.key(forked), TeachingPosition.key(g), "fork retains complete undo state")
    var handicap := GoGame.new(9, 0.5, 5)
    var query := TeachingPosition.query(handicap, "fixture")
    t.eq(query["initialStones"].size(), 5, "handicap remains setup")
    t.eq(query["initialPlayer"], "W", "White starts handicap query")
    t.eq(query["maxVisits"], 30, "live budget is thirty visits")
    t.eq(query["includePolicy"], false, "live teaching does not request policy")
    handicap.play_xy(0,0)
    t.eq(TeachingPosition.query(handicap, "fixture")["moves"], [["W","A9"]], "full retained move history follows setup")
