## Where does the opponent stop, and what does it play on the way there?
##
##   godot --headless --path . --script res://tools/ai_endgame.gd
##   godot --headless --path . --script res://tools/ai_endgame.gd -- 13
##
## M28 measured two numbers by hand -- 139 moves to play out a 9x9 and 477 for a
## 13x13 -- and had nothing to re-run them with. This is that instrument, and it
## exists because "the AI's endgame is weak" was a sentence in three documents
## and a figure in none of the tests.
##
## The waste metric is deliberately measured with GoScoring.territory_map(), not
## with the opponent's own idea of what is settled: a policy that grades its own
## homework tells you it has stopped playing pointless moves at the exact moment
## it redefines pointless. territory_map is pure, is in src/go/, and is not
## touched by this milestone.
extends SceneTree

const GAMES := 24

var board := 9


func _initialize() -> void:
	for a in OS.get_cmdline_user_args():
		if a.is_valid_int():
			board = int(a)
	print("board %dx%d, %d games per pairing" % [board, board, GAMES])
	var pairings := {
		"kesh  vs kesh ": [_profile(0.24, 1), _profile(0.24, 1)],
		"wren  vs kesh ": [_profile(0.45, 0), _profile(0.24, 1)],
		"random vs kesh": [_profile(1.0, 0, "random"), _profile(0.24, 1)],
	}
	for name in pairings:
		var pair: Array = pairings[name]
		_run(str(name), pair[0], pair[1])
	quit()


func _profile(mistake: float, depth: int, engine := "heuristic") -> OpponentProfile:
	# Built in code rather than as a .tres: this is a measuring instrument, not
	# content, and data/opponents/ is generated by tools/gen_content.py.
	var p := OpponentProfile.new()
	p.engine = engine
	p.board_size = board
	p.komi = 5.5
	p.mistake_rate = mistake
	p.reading_depth = depth
	p.aggression = 1.0
	p.territory_bias = 1.0
	return p


func _run(name: String, black: OpponentProfile, white: OpponentProfile) -> void:
	var cells := board * board
	var guard := cells * 6
	var moves_total := 0
	var moves_worst := 0
	var wasted := 0
	var finished := 0
	var dame_left := 0
	var margin_total := 0.0
	var usec_total := 0
	var usec_worst := 0
	var decisions := 0

	for i in GAMES:
		var game := GoGame.new(board, 5.5, 0)
		var b := OpponentFactory.create(black, game)
		var w := OpponentFactory.create(white, game)
		seed(i)
		while game.state == GoGame.State.PLAYING and game.moves.size() < guard:
			var who: GoOpponent = b if game.to_move == GoBoard.BLACK else w
			var before := GoScoring.territory_map(game.board)
			var t0 := Time.get_ticks_usec()
			var mv: Dictionary = await who.choose_move(game)
			var spent := Time.get_ticks_usec() - t0
			usec_total += spent
			usec_worst = maxi(usec_worst, spent)
			decisions += 1
			match str(mv.get("type", "pass")):
				"move":
					var point := int(mv["point"])
					# A stone played onto a point somebody already owned: either
					# filling your own territory or dying inside theirs.
					if before[point] != GoBoard.EMPTY:
						wasted += 1
					if not game.play(point):
						game.pass_turn()
				"resign":
					game.resign(game.to_move)
				_:
					game.pass_turn()

		moves_total += game.moves.size()
		moves_worst = maxi(moves_worst, game.moves.size())
		if game.state == GoGame.State.SCORING:
			finished += 1
		var terr := GoScoring.territory_map(GoScoring.board_without_dead(
			game.board, GoScoring.estimate_dead(game.board)))
		for p in terr.size():
			if game.board.is_empty(p) and terr[p] == GoBoard.EMPTY:
				dame_left += 1
		var dead := GoScoring.estimate_dead(game.board)
		var s := GoScoring.score(game.board, dead, game.captures, game.komi, GoScoring.Rule.JAPANESE)
		margin_total += float(s["margin"])

	var g := float(GAMES)
	print("\n=== %s" % name)
	print("   moves            mean %6.1f   worst %4d   (%.2f per point)"
		% [moves_total / g, moves_worst, (moves_total / g) / float(cells)])
	print("   stones wasted    mean %6.1f   -- played onto a point already owned"
		% [wasted / g])
	print("   ended in passes  %3d / %d" % [finished, GAMES])
	print("   neutral left     mean %6.1f   -- empty points nobody enclosed" % [dame_left / g])
	print("   margin           mean %6.1f" % [margin_total / g])
	print("   move time        mean %6.2f ms  worst %6.2f ms"
		% [float(usec_total) / float(maxi(decisions, 1)) / 1000.0, float(usec_worst) / 1000.0])
