#!/usr/bin/env python3
"""Standalone profiles; never rewrite campaign configurations."""
from pathlib import Path
import re
from novice_cast import NOVICES
ROOT = Path(__file__).resolve().parents[1]
STYLES = {
    'balanced': {},
    'steady': {'chosenMoveTemperatureEarly': .80, 'chosenMoveTemperature': .65, 'staticScoreUtilityFactor': .45},
    'fighting': {'chosenMoveTemperatureEarly': 1.05, 'chosenMoveTemperature': .90,
                 'staticScoreUtilityFactor': .15, 'humanSLRootExploreProbWeightless': .10,
                 'humanSLRootExploreProbWeightful': .10},
}
def beginner_temperature(rank):
    anchors = sorted((30-int(n['rank'][:-1]), n['temperature']) for n in NOVICES)
    for (a, av), (b, bv) in zip(anchors, anchors[1:]):
        if a <= rank <= b:
            return av + (bv-av)*(rank-a)/(b-a)
    raise ValueError(rank)
def config(rank, style):
    text = (ROOT/'packaging/katago/config/gtp_human_fast.cfg').read_text()
    label = f'{30-rank}k' if rank < 30 else f'{rank-29}d'
    values = dict(STYLES[style], humanSLProfile='preaz_'+(label if rank >= 10 else '20k'))
    if rank < 10:
        values.update(chosenMoveTemperatureEarly=beginner_temperature(rank),
                      chosenMoveTemperature=beginner_temperature(rank), chosenMoveTemperatureOnlyBelowProb=1.0)
    for key, value in values.items():
        text = re.sub(rf'(?m)^{key}\s*=.*$', f'{key} = {value}', text)
    return '# Generated by tools/gen_practice_profiles.py. Beginner ranks are approximate.\n'+text

def build():
    dest = ROOT/'packaging/katago/config/practice'
    dest.mkdir(exist_ok=True)
    for rank in range(35):
        label = f'{30-rank}k' if rank < 30 else f'{rank-29}d'
        for style in STYLES:
            (dest/f'{label}_{style}.cfg').write_text(config(rank, style))
if __name__ == '__main__': build()
