"""Writes the Godot TileSet resource from the tileset manifest.

Generated rather than hand-authored so tile names and atlas coordinates can
never disagree with the PNG.
"""
import json
import os
import sys

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.join(here, "..")


def build():
    man = json.load(open(os.path.join(root, "art", "tiles", "tileset_manifest.json")))
    ts = man["tile_size"]
    lines = [
        '; Generated by tools/gen_tileset_resource.py -- do not edit by hand.',
        '[gd_resource type="TileSet" load_steps=3 format=3]',
        '',
        '[ext_resource type="Texture2D" path="res://art/tiles/town_tileset.png" id="1_tex"]',
        '',
        '[sub_resource type="TileSetAtlasSource" id="TileSetAtlasSource_town"]',
        'texture = ExtResource("1_tex")',
        'texture_region_size = Vector2i(%d, %d)' % (ts, ts),
    ]
    for name, (cx, cy) in sorted(man["tiles"].items(), key=lambda kv: (kv[1][1], kv[1][0])):
        lines.append("%d:%d/0 = 0" % (cx, cy))
    lines += [
        '',
        '[resource]',
        'tile_size = Vector2i(%d, %d)' % (ts, ts),
        'sources/0 = SubResource("TileSetAtlasSource_town")',
        '',
    ]
    out = os.path.join(root, "art", "tiles", "town_tileset.tres")
    open(out, "w").write("\n".join(lines))
    return out, len(man["tiles"])


if __name__ == "__main__":
    print(build())
