## Does the review actually say anything, and is it saying the right things?
##
## The unit tests prove each detector fires on a board built to make it fire.
## That is necessary and it is not the question. The question is what a real
## game produces: how often there is anything to say at all, how often the
## review can honour its own rule and open with something the player did, and
## whether one kind has swallowed the whole review.
##
##   godot --headless --path . --script res://tools/review_distribution.gd
##
## READ THIS BEFORE BELIEVING THE NUMBERS. The heuristic opponent is not a
## beginner. mistake_rate used to substitute a uniformly random legal move; it
## now picks from a ranked shortlist -- "a 20 kyu does not play a random point
## on the board, they play the fourth-best move, confidently" -- and with
## SELF_ATARI_PENALTY on top it will essentially never self-atari, fill its own
## eye, or wander onto the first line. That is a much better opponent and a much
## worse *subject*: a review measured against it under-reports exactly the
## mistakes a four-day human makes constantly. So three player models are run,
## random being the noisy floor, and every number here is a LOWER BOUND on what
## a person triggers rather than an estimate of it.
extends SceneTree

const GAMES := 60
const MAX_MOVES := 160
const STRENGTHS := [8, 11, 15]        # 22k, 19k, 15k


func _initialize() -> void:
	var models := {
		"random           ": _profile("random", 1.0, 0),
		"heuristic  0.85  ": _profile("heuristic", 0.85, 0),
		"heuristic  0.45  ": _profile("heuristic", 0.45, 0),   # wren_9x9's rate
	}
	var opponent := _profile("heuristic", 0.24, 1)             # kesh_9x9's

	for name in models:
		print("\n=== player model: %s  (%d games vs a 12k)" % [name.strip_edges(), GAMES])
		var games: Array = []
		for i in GAMES:
			games.append(await _play_out(models[name], opponent, i))
		for strength in STRENGTHS:
			_report(games, strength)
	quit()


static func _profile(engine: String, mistake: float, depth: int) -> OpponentProfile:
	# Built in code rather than as a .tres: this is a measuring instrument, not
	# content, and data/opponents/ is generated by tools/gen_content.py.
	var p := OpponentProfile.new()
	p.engine = engine
	p.board_size = 9
	p.komi = 5.5
	p.mistake_rate = mistake
	p.reading_depth = depth
	p.aggression = 1.0
	p.territory_bias = 1.0
	return p


func _play_out(black: OpponentProfile, white: OpponentProfile, seed: int) -> GoGame:
	var game := GoGame.new(9, 5.5, 0)
	var b := OpponentFactory.create(black, game)
	var w := OpponentFactory.create(white, game)
	seed(seed)
	while game.state == GoGame.State.PLAYING and game.moves.size() < MAX_MOVES:
		var who: GoOpponent = b if game.to_move == GoBoard.BLACK else w
		var mv: Dictionary = await who.choose_move(game)
		match str(mv.get("type", "pass")):
			"move":
				if not game.play(int(mv["point"])):
					game.pass_turn()
			"resign":
				game.resign(game.to_move)
			_:
				game.pass_turn()
	return game


func _report(games: Array, strength: int) -> void:
	var reviewed := 0
	var opened_well := 0
	var two_plus := 0
	var kinds := {}
	var costs := {}
	var total := 0

	for game in games:
		var found := GoReview.findings(game, GoBoard.BLACK, strength)
		if found.is_empty():
			continue
		reviewed += 1
		if bool(found[0].get("good", false)):
			opened_well += 1
		if found.size() >= 2:
			two_plus += 1
		for f in found:
			var k := str(f["kind"])
			kinds[k] = int(kinds.get(k, 0)) + 1
			costs[k] = float(costs.get(k, 0.0)) + float(f.get("cost", 0.0))
			total += 1

	print("  -- at strength %d (%s)" % [strength, GoRank.to_string_rank(strength)])
	print("     reviewed        %3d / %d games" % [reviewed, games.size()])
	print("     opened w/ praise%3d / %d  %s" % [opened_well, reviewed,
		"OK" if opened_well == reviewed else "*** SHOULD BE ALL OF THEM ***"])
	print("     two or more     %3d / %d" % [two_plus, games.size()])
	if total == 0:
		return
	var names := kinds.keys()
	names.sort()
	for k in names:
		var n: int = int(kinds[k])
		var share := 100.0 * float(n) / float(total)
		print("       %-22s %3d  %5.1f%%  mean cost %5.1f%s" % [k, n, share,
			float(costs[k]) / float(n),
			"   *** DOMINATES ***" if share > 40.0 else ""])
